default_language_version:
  python: python
repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python

  - repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  -   repo: local
      hooks:
          -   id: spectacular-validate
              name: spectacular validate OpenAPI
              language: system            # важное: не python, не script — чтобы не требовался bash
              entry: python src/manage.py spectacular --validate --fail-on-warn --file src/schema.yaml
              pass_filenames: false       # manage.py не принимает список файлов от pre-commit
              stages: [ pre-commit, manual ]    # можно добавить push, если хочешь
              env:
                  DJANGO_SETTINGS_MODULE: config.settings.dev
