# Generated by Django 5.2.7 on 2026-03-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AmoPipeline',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'amo_pipelines',
            },
        ),
        migrations.CreateModel(
            name='AmoStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                (
                    'pipeline',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='statuses',
                        to='analytics.amopipeline',
                    ),
                ),
            ],
            options={
                'db_table': 'amo_statuses',
            },
        ),
        migrations.CreateModel(
            name='AmoLeadTransition',
            fields=[
                ('event_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('lead_id', models.IntegerField(db_index=True)),
                ('at', models.IntegerField(db_index=True)),
                ('by_user', models.IntegerField(blank=True, null=True)),
                (
                    'from_status',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='transitions_from',
                        to='analytics.amostatus',
                    ),
                ),
                (
                    'to_status',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='transitions_to',
                        to='analytics.amostatus',
                    ),
                ),
            ],
            options={
                'db_table': 'amo_lead_transitions',
            },
        ),
        migrations.AddIndex(
            model_name='amostatus',
            index=models.Index(fields=['pipeline'], name='amo_statuse_pipelin_6410d9_idx'),
        ),
        migrations.AddIndex(
            model_name='amostatus',
            index=models.Index(fields=['is_final'], name='amo_statuse_is_fina_d6fd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='amoleadtransition',
            index=models.Index(fields=['lead_id', 'at'], name='amo_lead_tr_lead_id_e3ec76_idx'),
        ),
        migrations.AddIndex(
            model_name='amoleadtransition',
            index=models.Index(fields=['at'], name='amo_lead_tr_at_2d8386_idx'),
        ),
    ]
