# Generated by Django 5.2.7 on 2026-03-25 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoLead',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512)),
                (
                    'price',
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.IntegerField(blank=True, null=True)),
                ('responsible_user_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('raw_json', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'amo_leads',
            },
        ),
        migrations.CreateModel(
            name='AmoLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_type', models.CharField(max_length=32)),
                ('from_id', models.IntegerField()),
                ('to_type', models.CharField(max_length=32)),
                ('to_id', models.IntegerField()),
                ('link_type', models.CharField(blank=True, max_length=64)),
                ('raw_json', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'amo_links',
            },
        ),
        migrations.CreateModel(
            name='AmoTask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, max_length=32)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('complete_till', models.IntegerField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.IntegerField(blank=True, null=True)),
                ('responsible_user_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('raw_json', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'amo_tasks',
            },
        ),
        migrations.AddIndex(
            model_name='amoleadtransition',
            index=models.Index(fields=['from_status', 'at'], name='amo_lead_tr_from_st_5aedb5_idx'),
        ),
        migrations.AddIndex(
            model_name='amoleadtransition',
            index=models.Index(fields=['to_status', 'at'], name='amo_lead_tr_to_stat_c45bb5_idx'),
        ),
        migrations.AddField(
            model_name='amolead',
            name='pipeline',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='leads',
                to='analytics.amopipeline',
            ),
        ),
        migrations.AddField(
            model_name='amolead',
            name='status',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='leads',
                to='analytics.amostatus',
            ),
        ),
        migrations.AddIndex(
            model_name='amolink',
            index=models.Index(
                fields=['from_type', 'from_id'], name='amo_links_from_ty_2836ce_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='amolink',
            index=models.Index(fields=['to_type', 'to_id'], name='amo_links_to_type_30bbbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='amolink',
            constraint=models.UniqueConstraint(
                fields=('from_type', 'from_id', 'to_type', 'to_id', 'link_type'),
                name='amo_links_unique_edge',
            ),
        ),
        migrations.AddIndex(
            model_name='amotask',
            index=models.Index(
                fields=['entity_type', 'entity_id'], name='amo_tasks_entity__db7a16_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='amotask',
            index=models.Index(fields=['responsible_user_id'], name='amo_tasks_respons_63db7a_idx'),
        ),
        migrations.AddIndex(
            model_name='amolead',
            index=models.Index(fields=['pipeline', 'price'], name='amo_leads_pipelin_488942_idx'),
        ),
        migrations.AddIndex(
            model_name='amolead',
            index=models.Index(fields=['pipeline', 'status'], name='amo_leads_pipelin_1e16ad_idx'),
        ),
    ]
