# Generated by Django 5.2.7 on 2026-03-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_amolead_amolink_amotask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoSyncState',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('watermark_updated_at', models.BigIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'amo_sync_state',
            },
        ),
    ]
